# Generated by Django 6.1 on 2026-08-28 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pitchbooking",
            name="booking_type",
            field=models.CharField(
                choices=[
                    ("FIXTURE", "Fixture"),
                    ("GROUND_MAINTENANCE", "Ground Maintenance"),
                ],
                default="FIXTURE",
                max_length=25,
            ),
        ),
    ]
