# Generated by Django 6.0.5 on 2026-07-23 20:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bookings", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingchangerequest",
            name="requested_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="pitch",
            name="blocks_pitches",
            field=models.ManyToManyField(blank=True, null=True, to="bookings.pitch"),
        ),
        migrations.AddField(
            model_name="bookingchangerequest",
            name="new_pitch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="bookings.pitch",
            ),
        ),
        migrations.AddField(
            model_name="pitchbooking",
            name="fixture",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="bookings.fixture",
            ),
        ),
        migrations.AddField(
            model_name="pitchbooking",
            name="pitch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="bookings.pitch"
            ),
        ),
        migrations.AddField(
            model_name="pitchbooking",
            name="requested_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="cateringrequest",
            name="booking",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="catering_request",
                to="bookings.pitchbooking",
            ),
        ),
        migrations.AddField(
            model_name="bookingchangerequest",
            name="original_booking",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="change_requests",
                to="bookings.pitchbooking",
            ),
        ),
        migrations.AddField(
            model_name="pitch",
            name="supported_lengths",
            field=models.ManyToManyField(blank=True, to="bookings.pitchlength"),
        ),
        migrations.AddField(
            model_name="team",
            name="managers",
            field=models.ManyToManyField(
                blank=True, related_name="managed_teams", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="required_length",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="bookings.pitchlength",
            ),
        ),
        migrations.AddField(
            model_name="fixture",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="bookings.team"
            ),
        ),
        migrations.AddField(
            model_name="pitch",
            name="venue",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pitches",
                to="bookings.venue",
            ),
        ),
    ]
