# Generated by Django 6.1 on 2026-08-29 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0003_pitchbooking_booking_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="pitch",
            name="is_outfield",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="pitchbooking",
            name="pitch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="bookings.pitch",
            ),
        ),
    ]
