# Generated by Django 6.1 on 2026-08-29 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0004_pitch_is_outfield_alter_pitchbooking_pitch"),
    ]

    operations = [
        migrations.AddField(
            model_name="pitch",
            name="pitch_category",
            field=models.CharField(
                choices=[("MAIN", "Main Pitch"), ("YOUTH", "Youth Pitch")],
                default="MAIN",
                max_length=10,
            ),
        ),
    ]
