# Generated by Django 6.1 on 2026-08-29 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0005_pitch_pitch_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pitch",
            name="is_outfield",
        ),
        migrations.RemoveField(
            model_name="pitch",
            name="pitch_category",
        ),
        migrations.AddField(
            model_name="pitch",
            name="entity_type",
            field=models.CharField(
                choices=[
                    ("PITCH", "Pitch"),
                    ("OUTFIELD", "Outfield Area"),
                    ("NET", "Batting Net"),
                ],
                default="PITCH",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="pitch",
            name="blocks_pitches",
            field=models.ManyToManyField(blank=True, to="bookings.pitch"),
        ),
    ]
