# Generated by Django 6.1.1 on 2026-09-05 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_remove_pitch_is_outfield_remove_pitch_pitch_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pitch',
            name='entity_type',
            field=models.CharField(choices=[('MAIN', 'Main Pitch'), ('YOUTH', 'Youth Pitch'), ('OUTFIELD', 'Outfield Area'), ('NET', 'Batting Net')], default='MAIN', max_length=10),
        ),
    ]
